import { BaseComponentProps } from "../../types";

export type IconName =
  | "x-com"
  | "whatsapp"
  | "wechat"
  | "user-verify"
  | "ticket"
  | "telegram-circle"
  | "swap-horizontal"
  | "star"
  | "sort-down"
  | "smart-phone"
  | "shopping-bag-remove"
  | "shield-done"
  | "time-circle"
  | "send-message"
  | "search"
  | "ringing"
  | "question-mark-circle"
  | "profile"
  | "plus"
  | "plus-2"
  | "plane-take-off"
  | "plane-take-off-line"
  | "plane-landing-line"
  | "plane-add"
  | "pin"
  | "pin-1"
  | "number-2-circle"
  | "number-1-circle"
  | "network-world"
  | "money-paper"
  | "minus"
  | "location"
  | "linkedin-square"
  | "link"
  | "line"
  | "kettlebell"
  | "instagram"
  | "info-menu"
  | "info-menu-1"
  | "info-circle"
  | "image"
  | "home"
  | "hide-3"
  | "hamburger-menu"
  | "grid-interface"
  | "grid-interface-add-plus"
  | "flight-ticket"
  | "flag"
  | "filter"
  | "facebook-circle"
  | "face-id-lock"
  | "eye"
  | "expand"
  | "error-triangle"
  | "edit"
  | "dollar-badge"
  | "document-2-lines"
  | "delivery"
  | "delivery-clock-time"
  | "delete"
  | "cube6"
  | "close-remove"
  | "clockwise-clock-redo"
  | "clipboard-add"
  | "circle"
  | "circle-clock"
  | "chevron-right-md"
  | "chevron-left-md"
  | "check-badge"
  | "caret-up-md"
  | "caret-down-md"
  | "calendar"
  | "calendar-2-line"
  | "building-office"
  | "board-menu"
  | "bag"
  | "arrows-vertical-expand"
  | "arrows-horizontal-expand"
  | "arrows-diagonal-expand"
  | "arrow-up-right_md"
  | "arrow-up-md"
  | "arrow-right-md"
  | "arrow-left-md"
  | "arrow-down-md"
  | "ai-square-spark-add"
  | "add-username"
  | "star-bold"
  | "quotation-open"
  | "quotation-close"
  | "pin-2"
  | "diamond"
  | "close-square"
  | "check-circle"
  | "check-badge-2"
  | "right-up-square"
  | "password-lock"
  | "logout"
  | "bag-2"
  | "world-location"
  | "share-4"
  | "login"
  | "arrow-down-left_md"
  | "minus-2"
  | "messages"
  | "loading"
  | "folder-file-open"
  | "youtube"
  | "checkmark"
  | "inbox-down"
  | "inbox-up"
  | "replay-square-3"
  | "play"
  | "pause"
  | "password-lock-2"
  | "lock"
  | "location-2"
  | "hide"
  | "delivery-close"
  | "user-lock"
  | "smiling"
  | "setting"
  | "seen-checkmark"
  | "right-side"
  | "polygon"
  | "pentagon"
  | "messages-close"
  | "lock-open"
  | "left-side"
  | "diamond-2"
  | "check-circle-2"
  | "x com"
  | "whatsapp"
  | "wechat"
  | "user verify"
  | "ticket"
  | "telegram circle"
  | "swap horizontal"
  | "star"
  | "sort down"
  | "smart phone"
  | "shopping bag remove"
  | "shield done"
  | "time circle"
  | "send message"
  | "search"
  | "ringing"
  | "question mark circle"
  | "profile"
  | "plus"
  | "plus 2"
  | "plane take off"
  | "plane take off line"
  | "plane landing line"
  | "plane add"
  | "pin"
  | "pin 1"
  | "number 2 circle"
  | "number 1 circle"
  | "network world"
  | "money paper"
  | "minus"
  | "location"
  | "linkedin square"
  | "link"
  | "line"
  | "kettlebell"
  | "instagram"
  | "info menu"
  | "info menu 1"
  | "info circle"
  | "image"
  | "home"
  | "hide 3"
  | "hamburger menu"
  | "grid interface"
  | "grid interface add plus"
  | "flight ticket"
  | "flag"
  | "filter"
  | "facebook circle"
  | "face id lock"
  | "eye"
  | "expand"
  | "error triangle"
  | "edit"
  | "dollar badge"
  | "document 2 lines"
  | "delivery"
  | "delivery clock time"
  | "delete"
  | "cube6"
  | "close remove"
  | "clockwise clock redo"
  | "clipboard add"
  | "circle"
  | "circle clock"
  | "chevron right md"
  | "chevron left md"
  | "check badge"
  | "caret up md"
  | "caret down md"
  | "calendar"
  | "calendar 2 line"
  | "building office"
  | "board menu"
  | "bag"
  | "arrows vertical expand"
  | "arrows horizontal expand"
  | "arrows diagonal expand"
  | "arrow up right_md"
  | "arrow up md"
  | "arrow right md"
  | "arrow left md"
  | "arrow down md"
  | "ai square spark add"
  | "add username"
  | "star bold"
  | "quotation open"
  | "quotation close"
  | "pin 2"
  | "diamond"
  | "close square"
  | "check circle"
  | "check badge 2"
  | "right up square"
  | "password lock"
  | "logout"
  | "bag 2"
  | "world location"
  | "share 4"
  | "login"
  | "arrow down left_md"
  | "minus 2"
  | "messages"
  | "loading"
  | "folder file open"
  | "youtube"
  | "checkmark"
  | "inbox down"
  | "inbox up"
  | "replay square 3"
  | "play"
  | "pause"
  | "password lock 2"
  | "lock"
  | "location 2"
  | "hide"
  | "delivery close"
  | "user lock"
  | "smiling"
  | "setting"
  | "seen checkmark"
  | "right side"
  | "polygon"
  | "pentagon"
  | "messages close"
  | "lock open"
  | "left side"
  | "diamond 2"
  | "check circle 2"
  | "up-line"
  | "up line"
  | "down-line"
  | "down line"
  | "user-star"
  | "user star"
  | "copy"
  | "Copy"
  | (string & {});

export type CaseInsensitive<T extends string> =
  | Uppercase<T>
  | Lowercase<T>
  | Capitalize<Lowercase<T>>;

export interface IconProps extends BaseComponentProps {
  name: IconName;
  onClick?: () => void;
}
