# Generated by Django 5.0.4 on 2024-08-08 14:10

import api.models.base
import api.models.temp_object
import api.utils
import django.db.models.deletion
from django.db import migrations, models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('city', models.CharField(max_length=200)),
                ('airport', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'Location',
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', api.models.temp_object.TypedJSONField(encoder=api.utils.DecimalEncoder)),
                ('destination', api.models.temp_object.TypedJSONField(encoder=api.utils.DecimalEncoder)),
                ('number', models.CharField(blank=True, max_length=20, null=True)),
                ('airline', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Flight'
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tickets/')),
                ('description', models.TextField(blank=True, null=True)),
                ('status', api.models.base.PeybarEnumField(choices=[('su', 'SUBMITTED'), ('ac', 'ACCEPTED'), ('pe', 'PENDING'), ('pr', 'PROCESSING'), ('de', 'DELIVERED'), ('re', 'REJECTED'), ('ca', 'CANCELED'), ('fi', 'FINISHED')], default='su', max_length=2)),
                ('flight', api.models.base.SBPForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.flight')),
                ('user', api.models.base.SBPForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Trip',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', api.models.base.SBPForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='api.trip'),
),
                ('type', api.models.base.PeybarEnumField(choices=[('sh', 'SHIPPING'), ('so', 'SHOPPING')], max_length=2)),
                ('properties', api.models.temp_object.MultipleTypedJSONField(encoder=api.utils.DecimalEncoder)),
                ('cost', api.models.temp_object.TypedJSONField(encoder=api.utils.DecimalEncoder)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', api.models.base.PeybarEnumField(choices=[('su', 'SUBMITTED'), ('ac', 'ACCEPTED'), ('pe', 'PENDING'), ('pr', 'PROCESSING'), ('de', 'DELIVERED'), ('re', 'REJECTED'), ('ca', 'CANCELED'), ('fi', 'FINISHED')], default='su', max_length=2)),
            ],
            options={
                'db_table': 'Service'
            },
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', api.models.temp_object.TypedJSONField(encoder=api.utils.DecimalEncoder)),
                ('source', api.models.temp_object.TypedJSONField(encoder=api.utils.DecimalEncoder)),
                ('destination', api.models.temp_object.TypedJSONField(encoder=api.utils.DecimalEncoder)),
                ('type', api.models.base.PeybarEnumField(choices=[('sh', 'SHIPPING'), ('so', 'SHOPPING')], max_length=2)),
                ('properties', api.models.temp_object.MultipleTypedJSONField(encoder=api.utils.DecimalEncoder)),
                ('comment', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/')),
                ('name', models.CharField(max_length=50)),
                ('status', api.models.base.PeybarEnumField(choices=[('su', 'SUBMITTED'), ('ac', 'ACCEPTED'), ('pe', 'PENDING'), ('pr', 'PROCESSING'), ('de', 'DELIVERED'), ('re', 'REJECTED'), ('ca', 'CANCELED'), ('fi', 'FINISHED')], default='su', max_length=2)),
                ('user', api.models.base.SBPForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Requirement',
            },
        ),
       migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal', api.models.temp_object.TypedJSONField(encoder=api.utils.DecimalEncoder)),
                ('status', api.models.base.PeybarEnumField(choices=[('su', 'SUBMITTED'), ('ac', 'ACCEPTED'), ('pe', 'PENDING'), ('pr', 'PROCESSING'), ('de', 'DELIVERED'), ('re', 'REJECTED'), ('ca', 'CANCELED'), ('fi', 'FINISHED')], default='su', max_length=2)),
                ('description', models.TextField(blank=True, null=True)),
                ('submit_time', models.DateTimeField(blank=True, null=True)),
                ('accept_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('accepted_by', api.models.base.SBPForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acceptor_requests', to=settings.AUTH_USER_MODEL)),
                ('requirement', api.models.base.SBPForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='api.requirement')),
                ('service', api.models.base.SBPForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='api.service')),
                ('submitted_by', api.models.base.SBPForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Request',
            },
        ),
        migrations.CreateModel(
            name='OrderStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', api.models.base.PeybarEnumField(choices=[('pa', 'PAYMENT'), ('de', 'DELIVER'), ('re', 'RECEIVE'), ('do', 'DONE')], max_length=2)),
                ('status', api.models.base.PeybarEnumField(choices=[('wa', 'WAITING'), ('pe', 'PENDING'), ('fa', 'FAILED'), ('do', 'DONE')], default='wa', max_length=2)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('properties', api.models.temp_object.MultipleTypedJSONField(encoder=api.utils.DecimalEncoder)),
                ('role', api.models.base.PeybarEnumField(choices=[('tr', 'TRAVELER'), ('cu', 'CUSTOMER')], max_length=2)),
                ('follow_step', api.models.base.SBPForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.orderstep')),
                ('user', api.models.base.SBPForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('request', api.models.base.SBPForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='api.request')),
            ],
            options={
                'db_table': 'OrderStep',
            },
        ),

        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wage', models.FloatField()),
                ('fee', models.FloatField(blank=True, null=True)),
                ('item_price', models.FloatField(blank=True, help_text='The estimated price of an item, whether it is a shipping or shopping. For shopping it is necessary.', null=True)),
                ('unit', api.models.base.PeybarEnumField(choices=[('us', 'USD'), ('eu', 'EURO'), ('ye', 'YEN')], default='us', max_length=2)),
            ],
            options={
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderStepPropertiesBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField()),
                ('traveler_fee', models.FloatField()),
                ('requester_fee', models.FloatField()),
            ],
            options={
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', api.models.temp_object.TempObjectForeignKey()),
                ('since', models.DateTimeField(blank=True, null=True)),
                ('to', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShippingDocumentProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', api.models.base.PeybarEnumField(choices=[('vi', 'VISIBLE_LOAD'), ('do', 'DOCUMENT')], default='do', max_length=2)),
                ('weight', models.FloatField()),
            ],
            options={
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShippingProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', api.models.base.PeybarEnumField(choices=[('do', 'DOCUMENT'), ('cl', 'CLOTH'), ('fo', 'FOOD'), ('el', 'ELECTRIC_GADGET'), ('ot', 'OTHER')], default='do', max_length=2)),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('width', models.FloatField()),
                ('length', models.FloatField()),
            ],
            options={
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShippingVisibleLoadProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', api.models.base.PeybarEnumField(choices=[('vi', 'VISIBLE_LOAD'), ('do', 'DOCUMENT')], default='vi', max_length=2)),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('width', models.FloatField()),
                ('length', models.FloatField()),
            ],
            options={
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShoppingProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', api.models.base.PeybarEnumField(choices=[('do', 'DOCUMENT'), ('cl', 'CLOTH'), ('fo', 'FOOD'), ('el', 'ELECTRIC_GADGET'), ('ot', 'OTHER')], default='cl', max_length=2)),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('width', models.FloatField()),
                ('length', models.FloatField()),
                ('link', models.URLField()),
            ],
            options={
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShoppingVisibleLoadProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', api.models.base.PeybarEnumField(choices=[('vi', 'VISIBLE_LOAD'), ('do', 'DOCUMENT')], default='vi', max_length=2)),
                ('weight', models.FloatField()),
            ],
            options={
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='userdocument',
            name='status',
            field=api.models.base.PeybarEnumField(choices=[('pe', 'PENDING'), ('ve', 'VERIFIED'), ('re', 'REJECTED'), ('fa', 'FAILED')], default='pe', max_length=2),
        ),
        migrations.CreateModel(
            name='CustomerDeliverProperties',
            fields=[
                ('ordersteppropertiesbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.ordersteppropertiesbase')),
                ('code', models.CharField(max_length=12)),
            ],
            options={
                'abstract': False,
                'managed': False,
            },
            bases=('api.ordersteppropertiesbase',),
        ),
        migrations.CreateModel(
            name='CustomerPaymentProperties',
            fields=[
                ('ordersteppropertiesbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.ordersteppropertiesbase')),
                ('link', models.URLField()),
            ],
            options={
                'abstract': False,
                'managed': False,
            },
            bases=('api.ordersteppropertiesbase',),
        ),
        migrations.CreateModel(
            name='CustomerReceiveProperties',
            fields=[
                ('ordersteppropertiesbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.ordersteppropertiesbase')),
                ('code', models.CharField(max_length=12)),
            ],
            options={
                'abstract': False,
                'managed': False,
            },
            bases=('api.ordersteppropertiesbase',),
        ),
        migrations.CreateModel(
            name='DoneProperties',
            fields=[
                ('ordersteppropertiesbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.ordersteppropertiesbase')),
                ('rate', models.PositiveIntegerField(default=5)),
            ],
            options={
                'abstract': False,
                'managed': False,
            },
            bases=('api.ordersteppropertiesbase',),
        ),
        migrations.CreateModel(
            name='TravelerDeliverProperties',
            fields=[
                ('ordersteppropertiesbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.ordersteppropertiesbase')),
                ('code', models.CharField(blank=True, max_length=12, null=True)),
            ],
            options={
                'abstract': False,
                'managed': False,
            },
            bases=('api.ordersteppropertiesbase',),
        ),
        migrations.CreateModel(
            name='TravelerPaymentProperties',
            fields=[
                ('ordersteppropertiesbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.ordersteppropertiesbase')),
            ],
            options={
                'abstract': False,
                'managed': False,
            },
            bases=('api.ordersteppropertiesbase',),
        ),
        migrations.CreateModel(
            name='TravelerReceiveProperties',
            fields=[
                ('ordersteppropertiesbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.ordersteppropertiesbase')),
                ('code', models.CharField(blank=True, max_length=12, null=True)),
            ],
            options={
                'abstract': False,
                'managed': False,
            },
            bases=('api.ordersteppropertiesbase',),
        ),
    ]
