# Generated by Django 5.1 on 2024-08-19 19:03

import api.models.base
import api.models.types
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_temp_objects'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='area',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.CharField(default='US', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='district',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='postal_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='type',
            field=api.models.base.PeybarEnumField(choices=[('ai', 'AIRPORT'), ('ho', 'HOME')], default='ai', enum_class=api.models.types.LocationType, max_length=2),
        ),
        migrations.AddField(
            model_name='location',
            name='user',
            field=api.models.base.SBPForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='location',
            name='zone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderstep',
            name='role',
            field=api.models.base.PeybarEnumField(choices=[('tr', 'TRAVELER'), ('cu', 'CUSTOMER')], enum_class=api.models.types.RoleType, max_length=2),
        ),
        migrations.AlterField(
            model_name='orderstep',
            name='status',
            field=api.models.base.PeybarEnumField(choices=[('wa', 'WAITING'), ('pe', 'PENDING'), ('fa', 'FAILED'), ('do', 'DONE')], default='wa', enum_class=api.models.types.StepStatus, max_length=2),
        ),
        migrations.AlterField(
            model_name='orderstep',
            name='type',
            field=api.models.base.PeybarEnumField(choices=[('pa', 'PAYMENT'), ('de', 'DELIVER'), ('re', 'RECEIVE'), ('do', 'DONE')], enum_class=api.models.types.StepType, max_length=2),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=api.models.base.PeybarEnumField(choices=[('su', 'SUBMITTED'), ('ac', 'ACCEPTED'), ('pe', 'PENDING'), ('pr', 'PROCESSING'), ('de', 'DELIVERED'), ('re', 'REJECTED'), ('ca', 'CANCELED'), ('fi', 'FINISHED')], default='su', enum_class=api.models.types.ActionStatus, max_length=2),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='status',
            field=api.models.base.PeybarEnumField(choices=[('su', 'SUBMITTED'), ('ac', 'ACCEPTED'), ('pe', 'PENDING'), ('pr', 'PROCESSING'), ('de', 'DELIVERED'), ('re', 'REJECTED'), ('ca', 'CANCELED'), ('fi', 'FINISHED')], default='su', enum_class=api.models.types.ActionStatus, max_length=2),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='type',
            field=api.models.base.PeybarEnumField(choices=[('sh', 'SHIPPING'), ('so', 'SHOPPING')], enum_class=api.models.types.ServiceType, max_length=2),
        ),
        migrations.AlterField(
            model_name='service',
            name='status',
            field=api.models.base.PeybarEnumField(choices=[('su', 'SUBMITTED'), ('ac', 'ACCEPTED'), ('pe', 'PENDING'), ('pr', 'PROCESSING'), ('de', 'DELIVERED'), ('re', 'REJECTED'), ('ca', 'CANCELED'), ('fi', 'FINISHED')], default='su', enum_class=api.models.types.ActionStatus, max_length=2),
        ),
        migrations.AlterField(
            model_name='service',
            name='type',
            field=api.models.base.PeybarEnumField(choices=[('sh', 'SHIPPING'), ('so', 'SHOPPING')], enum_class=api.models.types.ServiceType, max_length=2),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=api.models.base.PeybarEnumField(choices=[('su', 'SUBMITTED'), ('ac', 'ACCEPTED'), ('pe', 'PENDING'), ('pr', 'PROCESSING'), ('de', 'DELIVERED'), ('re', 'REJECTED'), ('ca', 'CANCELED'), ('fi', 'FINISHED')], default='su', enum_class=api.models.types.ActionStatus, max_length=2),
        ),
        migrations.AlterField(
            model_name='userdocument',
            name='status',
            field=api.models.base.PeybarEnumField(choices=[('pe', 'PENDING'), ('ve', 'VERIFIED'), ('re', 'REJECTED'), ('fa', 'FAILED')], default='pe', enum_class=api.models.types.UserDocumentStatus, max_length=2),
        ),
        migrations.AlterField(
            model_name='userdocument',
            name='type',
            field=api.models.base.PeybarEnumField(choices=[('em', 'EMAIL')], enum_class=api.models.types.UserDocumentType, max_length=2),
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', api.models.base.PeybarEnumField(choices=[('te', 'telegram'), ('in', 'instagram'), ('vi', 'viber'), ('wh', 'whatsapp'), ('fa', 'facebook')], enum_class=api.models.types.SocialType, max_length=2)),
                ('link', models.CharField(max_length=200)),
                ('verified', models.BooleanField(default=False)),
                ('user', api.models.base.SBPForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='socials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Social',
            },
        ),
    ]
