# Generated by Django 5.1 on 2024-08-22 16:35

import api.models.base
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_profile'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rates',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_orders',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderstep',
            name='follow_step',
            field=api.models.base.SBPOneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.orderstep'),
        ),
        migrations.CreateModel(
            name='UserComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('rate', models.PositiveIntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('commentor', api.models.base.SBPForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_comments', to=settings.AUTH_USER_MODEL)),
                ('object_type', api.models.base.SBPForeignKey(db_constraint=False, db_index=False, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('user', api.models.base.SBPForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserComment',
            },
        ),
    ]
