# Generated by Django 5.1 on 2024-08-29 16:29

import api.models.base
import api.models.types
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_add_user_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='submit_type',
            field=api.models.base.PeybarEnumField(choices=[('we', 'WEB'), ('mo', 'MOBILE'), ('go', 'GOOGLE')], default='we', enum_class=api.models.types.UserSubmitType, max_length=2),
        ),
    ]
