# Generated by Django 5.1 on 2024-09-02 10:38

import api.models.temp_object
import api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_add_image_to_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(max_length=4)),
                ('phone', models.PositiveIntegerField()),
                ('socials', models.JSONField()),
            ],
            options={
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=api.models.temp_object.TypedJSONField(blank=True, encoder=api.utils.DecimalEncoder, null=True),
        ),
    ]
