# Generated by Django 5.1 on 2024-10-01 10:50

import api.models.base
import api.models.types
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_change_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=api.models.base.PeybarEnumField(choices=[('su', 'SUBMITTED'), ('ac', 'ACCEPTED'), ('pe', 'PENDING'), ('pr', 'PROCESSING'), ('pa', 'PAYED'), ('de', 'DELIVERED'), ('re', 'REJECTED'), ('ca', 'CANCELED'), ('fi', 'FINISHED'), ('ex', 'EXPIRED'), ('rj', 'REJECTED')], default='su', enum_class=api.models.types.ActionStatus, max_length=2),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='status',
            field=api.models.base.PeybarEnumField(choices=[('su', 'SUBMITTED'), ('ac', 'ACCEPTED'), ('pe', 'PENDING'), ('pr', 'PROCESSING'), ('pa', 'PAYED'), ('de', 'DELIVERED'), ('re', 'REJECTED'), ('ca', 'CANCELED'), ('fi', 'FINISHED'), ('ex', 'EXPIRED'), ('rj', 'REJECTED')], default='su', enum_class=api.models.types.ActionStatus, max_length=2),
        ),
        migrations.AlterField(
            model_name='service',
            name='status',
            field=api.models.base.PeybarEnumField(choices=[('su', 'SUBMITTED'), ('ac', 'ACCEPTED'), ('pe', 'PENDING'), ('pr', 'PROCESSING'), ('pa', 'PAYED'), ('de', 'DELIVERED'), ('re', 'REJECTED'), ('ca', 'CANCELED'), ('fi', 'FINISHED'), ('ex', 'EXPIRED'), ('rj', 'REJECTED')], default='su', enum_class=api.models.types.ActionStatus, max_length=2),
        ),
        migrations.AlterField(
            model_name='social',
            name='type',
            field=api.models.base.PeybarEnumField(choices=[('te', 'telegram'), ('in', 'instagram'), ('vi', 'viber'), ('wh', 'whatsapp'), ('fa', 'facebook'), ('li', 'linkedin'), ('we', 'wechat'), ('ln', 'line')], enum_class=api.models.types.SocialType, max_length=2),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=api.models.base.PeybarEnumField(choices=[('su', 'SUBMITTED'), ('ac', 'ACCEPTED'), ('pe', 'PENDING'), ('pr', 'PROCESSING'), ('pa', 'PAYED'), ('de', 'DELIVERED'), ('re', 'REJECTED'), ('ca', 'CANCELED'), ('fi', 'FINISHED'), ('ex', 'EXPIRED'), ('rj', 'REJECTED')], default='su', enum_class=api.models.types.ActionStatus, max_length=2),
        ),
        migrations.AlterField(
            model_name='userdocument',
            name='type',
            field=api.models.base.PeybarEnumField(choices=[('em', 'EMAIL'), ('pn', 'PROFILE_NAME'), ('pp', 'PROFILE_PICTURE')], enum_class=api.models.types.UserDocumentType, max_length=2),
        ),
    ]
