# Generated by Django 5.1 on 2024-10-01 13:18

import api.models.base
import api.models.types
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_add_new_status_types'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='airlines/')),
            ],
            options={
                'db_table': 'Airline',
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', api.models.base.PeybarEnumField(choices=[('sm', 'SMALL'), ('me', 'MEDIUM'), ('bi', 'BIG')], enum_class=api.models.types.AirportType, max_length=2)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Airport',
            },
        ),
        migrations.RemoveField(
            model_name='location',
            name='airport',
        ),
        migrations.AddField(
            model_name='flight',
            name='status',
            field=api.models.base.PeybarEnumField(choices=[('su', 'SUBMITTED'), ('pe', 'PENDING'), ('st', 'STARTED'), ('fi', 'FINISHED')], default='pe', enum_class=api.models.types.FlightStatus, max_length=2),
        ),
        migrations.AddField(
            model_name='location',
            name='object_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='object_type',
            field=api.models.base.SBPForeignKey(blank=True, db_constraint=False, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='airline',
            field=api.models.base.SBPForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.airline'),
        ),
    ]
