# Generated by Django 5.1 on 2024-10-03 18:20

import api.models.base
import api.models.types
import api.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_add_airport'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', api.models.user.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='type',
            field=api.models.base.PeybarEnumField(choices=[('sm', 'SMALL'), ('me', 'MEDIUM'), ('la', 'LARGE')], enum_class=api.models.types.AirportType, max_length=2),
        ),
    ]
