# Generated by Django 5.1.2 on 2024-10-10 12:23

import api.models.base
import api.models.types
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_add_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('iso', models.CharField(max_length=10)),
                ('area_code', models.IntegerField()),
            ],
            options={
                'db_table': 'City',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('iso', models.CharField(max_length=10)),
                ('continent', models.CharField(max_length=30)),
                ('zip_code', models.IntegerField()),
            ],
            options={
                'db_table': 'Country',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('iso', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Language',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='background/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='current_location',
            field=api.models.base.SBPForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.location'),
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=api.models.base.PeybarEnumField(choices=[('pe', 'PENDING'), ('ve', 'VERIFIED'), ('bl', 'BLOCKED')], default='pe', enum_class=api.models.types.ProfileStatus, max_length=2),
        ),
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userdocument',
            name='device',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdocument',
            name='type',
            field=api.models.base.PeybarEnumField(choices=[('em', 'EMAIL'), ('pn', 'PROFILE_NAME'), ('pp', 'PROFILE_PICTURE'), ('re', 'REGISTER')], enum_class=api.models.types.UserDocumentType, max_length=2),
        ),
        migrations.AlterField(
            model_name='userdocument',
            name='user',
            field=api.models.base.SBPForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=api.models.base.SBPForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.city'),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=api.models.base.SBPForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='api.country'),
        ),
        migrations.AlterField(
            model_name='location',
            name='country',
            field=api.models.base.SBPForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.country'),
        ),
        migrations.AddField(
            model_name='profile',
            name='speak_languages',
            field=models.ManyToManyField(to='api.language'),
        ),
    ]
