# Generated by Django 5.1.2 on 2024-10-10 18:50

import api.models.base
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_add_new_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='iso',
        ),
        migrations.AddField(
            model_name='city',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='type',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='captial',
            field=api.models.base.SBPForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.city'),
        ),
        migrations.AddField(
            model_name='country',
            name='iso_2',
            field=models.CharField(default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='iso_3',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='region',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
