# Generated by Django 5.1.2 on 2024-10-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_add_new_fields_to_references'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='long_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
