# Generated by Django 5.1.2 on 2024-10-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_add_new_fields_to_references'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='airport_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='airport',
            name='iata_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='airport',
            name='website',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='name_ascii',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='polpulation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='city',
            name='province_ascii',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='city',
            name='area_code',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='city',
            name='iso',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='city',
            name='province',
            field=models.CharField(max_length=50),
        ),
    ]
