# Generated by Django 5.1.2 on 2024-10-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_add_new_fields_to_references'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
