# Generated by Django 5.1.2 on 2024-11-07 14:40

import api.models.base
import api.models.temp_object
import api.models.types
import api.models.user
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_add_visible_for_items'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPurchaseProperties',
            fields=[
                ('ordersteppropertiesbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.ordersteppropertiesbase')),
            ],
            options={
                'abstract': False,
                'managed': False,
            },
            bases=('api.ordersteppropertiesbase',),
        ),
        migrations.CreateModel(
            name='TravelerPurchaseProperties',
            fields=[
                ('ordersteppropertiesbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.ordersteppropertiesbase')),
            ],
            options={
                'abstract': False,
                'managed': False,
            },
            bases=('api.ordersteppropertiesbase',),
        ),
        migrations.AlterField(
            model_name='flight',
            name='destination',
            field=api.models.temp_object.TypedJSONField(encoder=api.models.temp_object.TypedJSONEncoder),
        ),
        migrations.AlterField(
            model_name='flight',
            name='source',
            field=api.models.temp_object.TypedJSONField(encoder=api.models.temp_object.TypedJSONEncoder),
        ),
        migrations.AlterField(
            model_name='flight',
            name='status',
            field=api.models.base.PeybarEnumField(choices=[('su', 'SUBMITTED'), ('ac', 'ACCEPTED'), ('pe', 'PENDING'), ('st', 'STARTED'), ('fi', 'FINISHED')], default='pe', enum_class=api.models.types.FlightStatus, max_length=2),
        ),
        migrations.AlterField(
            model_name='orderstep',
            name='properties',
            field=api.models.temp_object.MultipleTypedJSONField(encoder=api.models.temp_object.TypedJSONEncoder),
        ),
        migrations.AlterField(
            model_name='orderstep',
            name='type',
            field=api.models.base.PeybarEnumField(choices=[('pa', 'PAYMENT'), ('de', 'DELIVER'), ('pu', 'PURCHASE'), ('re', 'RECEIVE'), ('do', 'DONE')], enum_class=api.models.types.StepType, max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=api.models.temp_object.TypedJSONField(blank=True, encoder=api.models.temp_object.TypedJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='deal',
            field=api.models.temp_object.TypedJSONField(encoder=api.models.temp_object.TypedJSONEncoder),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=api.models.base.PeybarEnumField(choices=[('su', 'SUBMITTED'), ('ac', 'ACCEPTED'), ('pe', 'PENDING'), ('pr', 'PROCESSING'), ('pa', 'PAYED'), ('de', 'DELIVERED'), ('re', 'RECEIVED'), ('ca', 'CANCELED'), ('fi', 'FINISHED'), ('ex', 'EXPIRED'), ('rj', 'REJECTED')], default='su', enum_class=api.models.types.ActionStatus, max_length=2),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='cost',
            field=api.models.temp_object.TypedJSONField(encoder=api.models.temp_object.TypedJSONEncoder),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='destination',
            field=api.models.temp_object.TypedJSONField(encoder=api.models.temp_object.TypedJSONEncoder),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='properties',
            field=api.models.temp_object.MultipleTypedJSONField(encoder=api.models.temp_object.TypedJSONEncoder),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='source',
            field=api.models.temp_object.TypedJSONField(encoder=api.models.temp_object.TypedJSONEncoder),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='status',
            field=api.models.base.PeybarEnumField(choices=[('su', 'SUBMITTED'), ('ac', 'ACCEPTED'), ('pe', 'PENDING'), ('pr', 'PROCESSING'), ('pa', 'PAYED'), ('de', 'DELIVERED'), ('re', 'RECEIVED'), ('ca', 'CANCELED'), ('fi', 'FINISHED'), ('ex', 'EXPIRED'), ('rj', 'REJECTED')], default='su', enum_class=api.models.types.ActionStatus, max_length=2),
        ),
        migrations.AlterField(
            model_name='service',
            name='cost',
            field=api.models.temp_object.TypedJSONField(encoder=api.models.temp_object.TypedJSONEncoder),
        ),
        migrations.AlterField(
            model_name='service',
            name='properties',
            field=api.models.temp_object.MultipleTypedJSONField(encoder=api.models.temp_object.TypedJSONEncoder),
        ),
        migrations.AlterField(
            model_name='service',
            name='status',
            field=api.models.base.PeybarEnumField(choices=[('su', 'SUBMITTED'), ('ac', 'ACCEPTED'), ('pe', 'PENDING'), ('pr', 'PROCESSING'), ('pa', 'PAYED'), ('de', 'DELIVERED'), ('re', 'RECEIVED'), ('ca', 'CANCELED'), ('fi', 'FINISHED'), ('ex', 'EXPIRED'), ('rj', 'REJECTED')], default='su', enum_class=api.models.types.ActionStatus, max_length=2),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=api.models.base.PeybarEnumField(choices=[('su', 'SUBMITTED'), ('ac', 'ACCEPTED'), ('pe', 'PENDING'), ('pr', 'PROCESSING'), ('pa', 'PAYED'), ('de', 'DELIVERED'), ('re', 'RECEIVED'), ('ca', 'CANCELED'), ('fi', 'FINISHED'), ('ex', 'EXPIRED'), ('rj', 'REJECTED')], default='su', enum_class=api.models.types.ActionStatus, max_length=2),
        ),
        migrations.CreateModel(
            name='UserFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=api.models.user.upload_to)),
                ('object_id', models.PositiveBigIntegerField()),
                ('field_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', api.models.base.PeybarEnumField(choices=[('pe', 'PENDING'), ('ve', 'VERIFIED'), ('re', 'REJECTED'), ('fa', 'FAILED')], default='pe', enum_class=api.models.types.UserDocumentStatus, max_length=2)),
                ('device', models.JSONField(blank=True, null=True)),
                ('object_type', api.models.base.SBPForeignKey(db_constraint=False, db_index=False, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('owner', api.models.base.SBPForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserFile',
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='profile',
            name='background',
            field=api.models.base.SBPForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backgrounds', to='api.userfile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=api.models.base.SBPForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avatars', to='api.userfile'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='image',
            field=api.models.base.SBPForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.userfile'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='image',
            field=api.models.base.SBPForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.userfile'),
        ),
    ]
