# Generated by Django 5.1.2 on 2024-11-24 11:18

import api.models.user
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_add_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='file',
            field=api.models.user.UserFileWithSymlink(upload_to=api.models.user.upload_to),
        ),
    ]
