# Generated by Django 5.1.2 on 2025-01-14 12:24

import api.models.base
import api.models.types
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_add_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='type',
            field=api.models.base.PeybarEnumField(choices=[('pe', 'Personal'), ('bu', 'Business')], default='pe', enum_class=api.models.types.ProfileType, max_length=2),
        ),
    ]
