# Generated by Django 5.1.2 on 2025-02-06 10:57

import api.models.base
import api.models.types
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_add_business_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='last_name',
        ),
        migrations.AddField(
            model_name='ticket',
            name='subscribe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='topic',
            field=api.models.base.PeybarEnumField(choices=[('bu', 'BUG'), ('he', 'HELP'), ('fr', 'FEATURE_REQUEST'), ('se', 'SECURITY_REPORT'), ('bi', 'BUSINESS'), ('in', 'INVEST'), ('ot', 'OTHER')], default='ot', enum_class=api.models.types.TicketType, max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=api.models.base.PeybarEnumField(choices=[('pe', 'PERSONAL'), ('bu', 'BUSINESS')], default='pe', enum_class=api.models.types.ProfileType, max_length=2),
        ),
    ]
