# Generated by Django 5.1.2 on 2025-01-16 14:07

import api.models.base
import api.models.types
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_add_business_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='area',
        ),
        migrations.RemoveField(
            model_name='location',
            name='district',
        ),
        migrations.RemoveField(
            model_name='location',
            name='zone',
        ),
        migrations.AddField(
            model_name='city',
            name='location',
            field=api.models.base.SBPForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='api.location'),
        ),
        migrations.AddField(
            model_name='country',
            name='location',
            field=api.models.base.SBPForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='countries', to='api.location'),
        ),
        migrations.AddField(
            model_name='location',
            name='parent',
            field=api.models.base.SBPForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=api.models.base.SBPForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='api.city'),
        ),
        migrations.AlterField(
            model_name='location',
            name='country',
            field=api.models.base.SBPForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='api.country'),
        ),
        migrations.AlterField(
            model_name='location',
            name='type',
            field=api.models.base.PeybarEnumField(choices=[('ai', 'AIRPORT'), ('ho', 'HOME'), ('pr', 'PRIVATE'), ('co', 'COUNTRY'), ('ci', 'CITY'), ('di', 'DISTRICT'), ('ar', 'AREA')], default='ai', enum_class=api.models.types.LocationType, max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=api.models.base.PeybarEnumField(choices=[('pe', 'PERSONAL'), ('bu', 'BUSINESS')], default='pe', enum_class=api.models.types.ProfileType, max_length=2),
        ),
    ]
