# Generated by Django 5.1.2 on 2025-01-16 14:32

import api.models.base
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_add_parent_for_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='city',
            field=api.models.base.SBPForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='api.city'),
        ),
    ]
