# Generated by Django 5.1.2 on 2025-02-06 11:44

import api.models.base
import api.models.types
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_add_new_report_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='EventSubscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=50)),
                ('subscribe_type', api.models.base.PeybarEnumField(choices=[('nl', 'NEWSLETTER')], default='nl', enum_class=api.models.types.SubscribeType, max_length=2)),
                ('user', api.models.base.SBPForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'EventSubscribe',
            },
        ),
    ]
