# Generated by Django 5.1.2 on 2025-01-16 17:41

import api.models.base
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_add_blank_city_country_to_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='destination',
            field=api.models.base.SBPForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.location'),
        ),
        migrations.AddField(
            model_name='trip',
            name='source',
            field=api.models.base.SBPForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.location'),
        ),
    ]
