# Generated by Django 5.1.2 on 2025-01-30 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_add_location_to_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='level',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='tag',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
