# Generated by Django 5.1.2 on 2025-02-06 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_add_new_report_fields'),
        ('api', '0025_add_location_tags'),
    ]

    operations = [
    ]
