# Generated by Django 5.1.2 on 2025-02-06 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_add_subscribe_table'),
        ('api', '0026_merge_20250206_1103'),
    ]

    operations = [
    ]
