# Generated by Django 5.2a1 on 2025-02-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_merge_20250206_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='readable_tag',
            field=models.CharField(default=None, max_length=200, null=True, unique=True),
        ),
    ]
