# Generated by Django 5.2a1 on 2025-02-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_add_readable_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PhoneNumber',
            new_name='OldPhoneNumber'
        ),
    ]
