# Generated by Django 5.2a1 on 2025-02-16 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_add_readable_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='polpulation',
            new_name='population',
        ),
        migrations.AddField(
            model_name='country',
            name='population',
            field=models.IntegerField(default=0),
        ),
    ]
