# Generated by Django 5.2a1 on 2025-02-14 12:53

import api.models.base
import api.models.types
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_add_user_contacts'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('phone', models.CharField(max_length=12)),
                ('zone_code', api.models.base.SBPForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.country')),
            ],
            options={
                'db_table': 'PhoneNumber',
            },
        ),
        migrations.CreateModel(
            name='UserContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('type', api.models.base.PeybarEnumField(choices=[('pn', 'PHONE_NUMBER'), ('so', 'SOCIAL')], enum_class=api.models.types.ContactType, max_length=2)),
                ('object_id', models.PositiveBigIntegerField()),
                ('object_type', api.models.base.SBPForeignKey(db_constraint=False, db_index=False, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('user', api.models.base.SBPForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserContact',
            },
        ),
    ]
