# Generated by Django 5.2a1 on 2025-02-19 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_change_field_population'),
        ('api', '0030_add_user_contacts'),
    ]

    operations = [
    ]
