# Generated by Django 5.2a1 on 2025-02-19 07:43

import api.models.cost
import api.models.location
import api.models.request
import api.models.requirement
import api.models.service
import api.models.temp_object
import api.models.user
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_merge_20250219_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='destination',
            field=api.models.temp_object.TypedJSONField(encoder=api.models.temp_object.TypedJSONEncoder, many=False, obj=api.models.location.Position, retrieve=None, store=None),
        ),
        migrations.AlterField(
            model_name='flight',
            name='source',
            field=api.models.temp_object.TypedJSONField(encoder=api.models.temp_object.TypedJSONEncoder, many=False, obj=api.models.location.Position, retrieve=None, store=None),
        ),
        migrations.AlterField(
            model_name='orderstep',
            name='properties',
            field=api.models.temp_object.MultipleTypedJSONField(encoder=api.models.temp_object.TypedJSONEncoder, many=False, objs=[api.models.request.TravelerPaymentProperties, api.models.request.CustomerPaymentProperties, api.models.request.CustomerPurchaseProperties, api.models.request.TravelerPurchaseProperties, api.models.request.CustomerDeliverProperties, api.models.request.CustomerReceiveProperties, api.models.request.TravelerReceiveProperties, api.models.request.TravelerDeliverProperties, api.models.request.DoneProperties], retrieve=None, store=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=api.models.temp_object.TypedJSONField(blank=True, encoder=api.models.temp_object.TypedJSONEncoder, many=False, null=True, obj=api.models.user.OldPhoneNumber, retrieve=None, store=None),
        ),
        migrations.AlterField(
            model_name='request',
            name='deal',
            field=api.models.temp_object.TypedJSONField(encoder=api.models.temp_object.TypedJSONEncoder, many=False, obj=api.models.request.Deal, retrieve=None, store=None),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='cost',
            field=api.models.temp_object.TypedJSONField(encoder=api.models.temp_object.TypedJSONEncoder, many=False, obj=api.models.cost.Cost, retrieve=None, store=None),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='destination',
            field=api.models.temp_object.TypedJSONField(encoder=api.models.temp_object.TypedJSONEncoder, many=False, obj=api.models.location.Position, retrieve=None, store=None),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='properties',
            field=api.models.temp_object.MultipleTypedJSONField(encoder=api.models.temp_object.TypedJSONEncoder, many=False, objs=[api.models.requirement.RequirementPropertiesShopping, api.models.requirement.RequirementPropertiesShipping], retrieve=None, store=None),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='source',
            field=api.models.temp_object.TypedJSONField(encoder=api.models.temp_object.TypedJSONEncoder, many=False, obj=api.models.location.Position, retrieve=None, store=None),
        ),
        migrations.AlterField(
            model_name='service',
            name='cost',
            field=api.models.temp_object.TypedJSONField(encoder=api.models.temp_object.TypedJSONEncoder, many=False, obj=api.models.cost.Cost, retrieve=None, store=None),
        ),
        migrations.AlterField(
            model_name='service',
            name='properties',
            field=api.models.temp_object.MultipleTypedJSONField(encoder=api.models.temp_object.TypedJSONEncoder, many=False, objs=[api.models.service.ServicePropertiesShopping, api.models.service.ServicePropertiesShipping,], retrieve=None, store=None),
        ),
    ]
