# Generated by Django 5.2a1 on 2025-02-19 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_change_typed_json_field'),
        ('api', '0033_change_old_data'),
    ]

    operations = [
    ]
