# Generated by Django 5.2a1 on 2025-02-19 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_merge_20250219_0745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='social',
            name='user',
        ),
    ]
